export default {
  history: {
    pageData: [
      {
        type: 'content',
        data: [
          { type: 'li', content: 'In 1983 David Chaum was the first man to describe digital currency and how anonymity is possible with virtual money (unlike with other options available during that time such as credit cards). He went on to invent DigiCash in 1989, the first-ever virtual currency. Unfortunately, DigiCash did not catch on because eCommerce began only in the mid-90s. Anonymity was not a major concern back then, and people were satisfied with spending money on credit cards, the familiar alternative.' },
          { type: 'li', content: 'This is just one isolated story out of many. Since then (or maybe since before then, according to a few reports), several such attempts at digital currency have been made by reputed pioneers. None of these trials was rewarded with any notable attention. The reasons for failure vary from security issues to trust issues.' },
          { type: 'li', content: 'In 2005, Nick Szabo proposed and developed ideas for a virtual currency called Bit Gold. He described it as a form of decentralized money, which can be created by solving problems on computer hardware. Upon generating proof of work, participants were rewarded with a piece of Bit Gold, which is time-stamped and recorded on a publicly-accessible registry, which in turn records every subsequent transfer data.' },
          { type: 'headLine', content: 'Bit Gold is one of the bench mark attempts at cryptocurrency and is speculated to have laid the path for Bitcoin.' },
          { type: 'li', content: 'Fast forward to 2008 and the global financial crisis. Call it a recession or call it the great depression, whatever the name, it was a wakeup call for the working population. They began to understand the extent to which governments and banks can influence the economy. Acting on this opportunity, a person or a group of people by the name Satoshi Nakamoto introduced to the word its first popular cryptocurrency – Bitcoin.' },
        ],
      },
    ],
  },
  basics: {
    pageData: [
      {
        type: 'content',
        data: [
          { type: 'question', content: 'What is Cryptocurrency?' },
          { type: 'answer', content: 'Cryptocurrency is defined as a decentralized (absence of a government or a 3 rd party involvement virtual currency (you cannot touch crypto like you would currency notes or coins) that uses cryptography technology.' },
          { type: 'question', content: 'What is Cryptography?' },
          { type: 'answer', content: 'The science of converting ordinary text to unintelligible data and vice versa is called cryptography. It involves decryption and subsequent encryption of data to ensure security in every form of communication.' },
          { type: 'question', content: 'What is Bitcoin and why is it important?' },
          { type: 'answer', content: 'Bitcoin (BTC) is a decentralized digital currency that enables instant payments to anyone, anywhere in the world. It uses peer-to-peer technology, which operates without a central intermediary body. Transactions are carried out in accordance with the network.' },
          { type: 'question', content: 'How divisible is Bitcoin?' },
          { type: 'answer', content: 'Bitcoin can be divided down to 8 decimal places. 0.00000001 BTC is the smallest quantity that can be treated as a single transaction.' },
        ],
      },
      {
        type: 'boxedContent',
        data: [
          { type: 'keyHeading', content: 'Key question' },
          { type: 'question2', content: 'What are the advantages of using Bitcoin?' },
          { type: 'abbreviation', word: 'Freedom of payment-', content: 'Bitcoins can be transferred and received instantly at any time and anywhere in the world. There are no borders, bank interests, or enforced limits. Bitcoin provides users with complete control over their money.' },
          { type: 'abbreviation', word: 'Extremely low fee-', content: 'Payments with Bitcoin are currently being processed with very low or no fee at all. Users can choose to pay extra when they need priority processing of the transfer.' },
          { type: 'abbreviation', word: 'Reduced risk of traders-', content: 'Bitcoin networks are secure, conclusive and do not record a customer’s sensitive or personal data. The network protects merchants against losses caused by fraud/fraudulent cancellations and eliminates the need for compliance with the rules of the payment card industry. Traders can easily reach new markets where credit card payment options are absent or considered risky.' },
          { type: 'abbreviation', word: 'Safety, control and management-', content: 'Bitcoin users enjoy complete control of their assets and transfers. One cannot get charged for anything without his knowledge and consent - as often is the case with other means of payments on the Internet. Payments with Bitcoin ensure high protection against identity theft. Users can secure their assets with an additional backup encryption.' },
          { type: 'abbreviation', word: 'Transaparency and neutrality-', content: 'Data on cash stock and remittance of bitcoins is publicly available in the chain blocks and visible to all. Everyone can view, review and make use of it at any time. No individual or organization can manipulate Bitcoin transaction data because the protocol is cryptographically secure.' },
        ],
      },
    ],
    contents: [
      'What is cryptocurrency?',
      'What is cryptography?',
      'What is Bitcoin and why is it important?',
      'How divisible is Bitcoin?',
      'What are the advantages of using Bitcoin?',
    ],
  },
  howTechnologyWorks: {
    pageData: [
      {
        type: 'content',
        data: [
          { type: 'question', content: 'What is Bitcoin mining?' },
          { type: 'li', content: 'Bitcoin mining is simply the process of producing new Bitcoins. Incredibly powerful computer systems are needed to work out complex mathematical problems(aptly called proof of work), which cannot be decoded by hand. Once successfully solved, the miners are rewarded with a block, thus producing newly minted Bitcoins.' },
          { type: 'li', content: 'These blocks are chained together, forming the blockchain. The entire history of bitcoin transactions is recorded in each of these computers. This step is incorporated to secure the network and verify every transaction.' },
          { type: 'question', content: 'What is Bitcoin node?' },
          { type: 'li', content: 'A node is just a computer that is running the bitcoin program and is connected to other electronic devices performing the same task, thus forming a network.' },
          { type: 'li', content: 'Each node checks the data it receives, passes on the information to other nodes, and most importantly maintains a copy of all confirmed transactions.' },
          { type: 'li', content: 'So every node has a copy of the blockchain, which it shares to the other nodes if their copy is not up to date.' },
          { type: 'li', content: 'Even if every other node in the world went offline for some reason, your node will still be upholding the entire bitcoin transaction network.' },
          { type: 'question', content: 'What is the transaction fee?' },
          { type: 'li', content: 'Miners are financially rewarded for solving complicated problems with –' },
          { type: 'li', content: 'This is the financial incentive offered to miners for their mining efforts and to ensure prioritization of transactions that include a higher fee.' },
          { type: 'li', content: 'This fee does not depend on the amount being transferred, as one might expect, but on the data size of the transaction and the network conditions.' },
          { type: 'li', content: 'Users can choose between a regular fee (when time is not a constraint) and a priority fee (when the transaction should be recorded within the hour).' },
          { type: 'question', content: 'Understand the concept of Halving' },
          { type: 'answer', content: 'When miners solve complex mathematical problems, they are rewarded with Bitcoins. Roughly every four years or after every 2,10,000 blocks, the number of Bitcoins that the miners win is halved. The system was started with 50 coins mined every 10 minutes. Now three halvings later this number diminished to 6.25. The process of halving will continue until the last Bitcoin is mined, most probably in 2140. The reasoning behind halving is to control the supply so that that demand is increased.' },
          { type: 'question', content: 'What is blockchain technology?' },
          { type: 'li', content: 'The first-ever block mined by Satoshi Nakamoto is known as the Genesis block. The subsequent block that was mined has a timestamp and a link to the Genesis block. Every time a new block is mined, it is connected sequentially to the previous block in the chain and not to the pilot block, thus forming the blockchain.' },
          { type: 'li', content: 'Each block signifies files where data (relating to the bitcoin network) are permanently recorded. Think of a block as a digital ledger, where information once recorded cannot be altered or removed. So each block contains data about the block preceding it (the past) and the block following it (the future), and once completed, gives way to a new block on the blockchain.' },
          { type: 'li', content: 'In simple terms, blockchain is a database. A distributed database to be specific because the power is scattered among several likeminded people and not verified by any central authority. This way, anything built on blockchain technology is not only transparent but also ensures trust, security and accountability.' },
          { type: 'li', content: 'This technology finds use outside the scope of bitcoins in many areas including and not limited to equity management, supply chain monitoring and election voting.' },
          { type: 'li', content: 'To sum up, using a quote by Marc Kenigsberg, Blockchain is the technology. Bitcoin is the first mainstream manifestation of its potential.' },
          { type: 'li', content: 'Now the bitcoin software is made available to the general public for mining. Once mined, Bitcoins (or any cryptocurrency for that matter) need a wallet to be stored.' },
        ],
      },
      {
        type: 'boxedContent',
        data: [
          { type: 'keyHeading', content: 'Key question' },
          { type: 'question2', content: 'What is a crypto wallet?' },
          { type: 'answer', content: 'A wallet is a place where you can store your cryptocurrency and perform transfers when needed. So your wallet address is essentially a random combination of digits and alphabets that signifies where your assets are saved. There are several Bitcoin wallets - both digital as well as paper.' },
          { type: 'question2', content: 'I have no wallet. How can I create one?' },
          { type: 'answer', content: 'You can create your own Bitcoin wallet on the web address: https://bitcoin.org/sl/izberite-denarnico' },
          { type: 'question2', content: 'What is the difference between a private key and a public key?' },
          { type: 'abbreviation', word: 'Private key: ', content: 'Once a user creates a wallet, a private key is generated as his/her identity in a blockchain- transaction. This key is a long unique number-sequence that is highly secure and is meant to be kept private.' },
          { type: 'abbreviation', word: 'Public key: ', content: 'Unlike private keys, public keys are intended to be shared with the others in the blockchain network. A user can generate multiple pubic keys, which when combined with private key form a digital signature that enables access to the transaction.' },
          { type: 'li', content: 'In simpler words, if Sara wants to send Tim information on the blockchain, she will get his public key (think of it as an email address), attach the particulars to it, and send it to him. Tim can access the data only by combining his private key (like he would, a password) with his public key. Note that Tim can give Helen a different public key to the one he gave Sara.' },
        ],
      },
      {
        type: 'boxedContent',
        data: [
          { type: 'keyHeading', content: 'Key concept' },
          { type: 'li', content: 'Note the fact that Bitcoin had no monetary value yet because it had only been mined and never traded.' },
          { type: 'li', content: 'In 2010, Laszlo Hanyecz made the first crypto purchase when he bought two pizzas for 10,000 BTC (approximately 700 crore INR or 91 million USD in today’s value), thus opening doors to a cryptocurrency market. Soon after, digital currency exchanges emerged and so did rivalling cryptocurrencies (now referred to as altcoins, short for alternate coins). By 2013 there were as any as 10 such virtual assets in the market.' },
          { type: 'li', content: 'The Cryptocurrency world has not been the same ever since. The idea of decentralised and encrypted currency signified that transferring funds between two parties was possible without any involvement of a 3 rd party (for example, a bank). The public enjoyed taking power away from banks.' },
        ],
      },
      {
        type: 'content',
        data: [
          { type: 'question', content: 'The birth of Ethereum' },
          { type: 'li', content: 'Inspired by Bitcoin, hundreds of imitators entered the market. One such notable mention is Ethereum. Its evelopment has been funded by an online crowd sale in 2014 and the system went live in 2015. Ethereum rose steadily and is today the second-largest cryptocurrency by market capitalization standard, right behind Bitcoin.' },
          { type: 'headLine', content: 'Bitcoin is still the best performing asset of the decade.' },
          { type: 'question', content: 'What is Ethereum?' },
          { type: 'li', content: 'Ethereum, similar to Bitcoin, is an open-source software platform which uses blockchain technology for its cryptocurrency. Whereas bitcoin is nothing more than a digital currency, Ethereum software is both – a virtual currency (Ether) and a network with applications that go beyond just enabling a digital currency to facilitate smart contracts that remain unchanged over time.' },
        ],
      },
    ],
    contents: [
      'What is Bitcoin mining?',
      'What is bitcoin node?',
      'What is the transaction fee?',
      'Understand the concept of Halving',
      'What is a crypto wallet?',
      'What is the difference between a private key and a public key?',
      'The birth of Ethereum',
      'What is Ethereum?',
    ],
  },
  fiatVsCryptocurrency: {
    pageData: [
      {
        type: 'content',
        data: [
          {
            type: 'li',
            content: 'Usually, a government (or a central authority) regulates the production of money in a country and generates the fiat currency. Since fiat is not backed by any physical commodity, its value is derived from the forces of supply and demand in the economy and the power to decide the said value relies on central banks and their rules. Governments can issue new policies from time to time that affect the value of money. Trillions of fiat currency can be printed with the click of a button, so one cannot ignore the risk of hyperinflation in such a situation.',
          },
          {
            type: 'li',
            content: 'With cryptocurrency, you are in control of your assets and the only one responsible for securing them. The blockchain technology ensures anonymity and transparency to the crypto transactions. This decentralization aspect of the network signifies that the value of a Bitcoin (or any such token) cannot be debased any a 3rd party authority figure. Inflations and recessions in the fiat world hardly scratch the crypto shield.',
          },
          {
            type: 'headLine',
            content: 'Bitcoin is freedom and bitcoin is your vote!',
          },
          { type: 'question', content: 'What is fiat currency?' },
          { type: 'answer', content: 'Fiat currency is government-issued money that is not backed by any commodity like gold or silver but rather by the government that issued it. The Indian rupee, the U.S dollar and the euro are all examples of fiat currency.' },
          { type: 'question', content: 'Inflation vs deflation' },
          { type: 'li', content: 'Over time, the value of fiat currency decreases because there is no limit to how much money the banks can print. The growth in the supply of money and the subsequent decrease in its value or buying power is called inflation. So by definition, most fiat currencies are inflationary. ' },
          { type: 'li', content: 'Bitcoin technology is deflationary. There can be infinite INR but only 21 million Bitcoins because that’s how the algorithm was designed. So as a result over time, Bitcoins become increasingly scarce, and so increasingly valuable.' },
          { type: 'headLine', content: 'If you still feel that Bitcoin is an experiment, don’t forget that so was fiat currency.' },
          { type: 'question', content: 'Where is crypto used today?' },
          { type: 'answer', content: 'Crypto assets are steadily gaining popularity to a point where adoption is now a necessity. The number of Bitcoin ATMs in the world is fast rising. More and more establishments are accepting payments in the form of cryptocurrencies. So essentially, Bitcoin is not just a store of value, but also a payment system in itself.' },
          { type: 'question', content: 'How safe and secure is bitcoin?' },
          { type: 'answer', content: 'Security has been of utmost importance for Bitcoin since its inception. The blockchain technology, which supports Bitcoin, makes acts such as theft, fraud and hacking highly unlikely. As the number of nodes added to the blockchain increases, so does its stability and security.' },
          { type: 'question', content: 'Is Bitcoin legal in India?' },
          { type: 'answer', content: 'Yes! The RBI banking ban on the crypto industry has now been effectively lifted. Both the Indian government and the RBI have confirmed that cryptocurrencies are legal in India. Read here to find out what the wizards of the financial world have to say about the verdict.' },
          { type: 'headLine', content: 'So what are you waiting for?' },
        ],
      },
    ],
    contents: [
      'What is fiat currency?',
      'Inflation vs deflation',
      'Where is crypto used today?',
      'How safe and secure is bitcoin?',
      'Is Bitcoin legal in India?',
    ],
  },
};
